[global]
workgroup = WORKGROUP
server string = Pi Photo Drive
security = user

[photos]
path = /srv/photos
browseable = yes
writable = yes
guest ok = no
valid users = photos
create mask = 0777
directory mask = 0777
